swagger: "2.0"
info:
  version: 1.0.0
  title: "codicesame"
  description: A simple chat system
  termsOfService: http://swagger.io/terms/
  contact:
    name: Mirko Schicchi
    email: mirko.schicchi@gmail.com
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: rocky-plains-88216.herokuapp.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /user:
    post:
      description: Insert a new user
      operationId: addUser
      parameters:
        - name: newUser
          in: body
          description: new user registered 
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: user created response
          schema:
            $ref: '#/definitions/User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /user/{id}:
    get:
      description: Return an user
      parameters:
        - name: id
          in: path
          description: ID of the user to fetch
          required: true
          type: string
      responses:
        200:
          description: OK - user
          schema:
            $ref: '#/definitions/User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      description: Update a user
      parameters:
        - name: id
          in: path
          description: Id of the room to update
          required: true
          type: string
        - name: user
          in: body
          description: user updated
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: OK - user updated
          schema:
            $ref: '#/definitions/User'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /room:
    post:
      description: Insert a new user
      parameters:
        - name: newRoom
          in: body
          description: New room
          required: true
          schema:
            $ref: '#/definitions/Room'
      responses:
        200: 
          description: OK - room inserted
          schema:
            $ref: '#/definitions/Room'
definitions:
  User:
    required:
      - userID
      - username
      - password
    properties:
      userID:
        type: string
      username:
        type: string
      password:
        type: string
  Room:
    required:
      - roomID
      - roomName
    properties:
      roomID:
        type: string
      roomName:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string